package org.company.myproject.model.types

enum class CompanyIndustry {
    BANKING_AND_FINANCE,
    CUSTOMER_SERVICE,
    EDUCATION_AND_RESEARCH,
    GAMING,
    HEALTHCARE,
    INFORMATION_TECHNOLOGY,
    INSURANCE,
    INTERNET,
    MANUFACTURING,
    MARKETING,
    MEDIA_AND_ENTERTAINMENT,
    PUBLISHING,
    PUBLIC_SECTOR,
    RETAIL,
    SPORTS_AND_EVENTS,
    TELECOMMUNICATIONS,
    TRANSPORTATION_AND_LOGISTICS,
    TRAVEL,
    UTILITIES,
    OTHER
}
