package org.osguima3.jooqdsl.plugin.context

import org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil
import org.jooq.meta.jaxb.Configuration
import org.jooq.meta.jaxb.ForcedType
import org.osguima3.jooqdsl.model.context.ModelContext
import org.osguima3.jooqdsl.model.context.TablesContext
import java.io.File
import java.io.SequenceInputStream
import kotlin.reflect.KClass

class ModelContextImpl(configuration: Configuration) : ModelContext {

    internal val targetPackage = configuration.generator.target.packageName

    internal val converterPackage = "$targetPackage.converters"

    internal val pendingTemplates = mutableSetOf<TemplateFile>()

    private val tablesContext = TablesContextImpl(this)

    private val forcedTypes = configuration.generator.database.forcedTypes

    private val targetDirectory = configuration.generator.target.directory

    private val converterDirectory = converterPackage.replace('.', '/')

    override fun tables(block: TablesContext.() -> Unit) = tablesContext.block()

    internal fun registerForcedType(expression: String, userType: KClass<*>, converter: String) = apply {
        forcedTypes += ForcedType().also {
            it.expression = expression
            it.userType = userType.qualifiedName
            it.converter = converter
        }
    }

    internal fun addTemplates(templates: Set<TemplateFile>) = apply {
        pendingTemplates.addAll(templates)
    }

    internal fun generateConverters() = pendingTemplates.map(TemplateFile::className).forEach {
        val source = this::class.java.classLoader.getResource("converter/$it.java")
        val target = File("$targetDirectory/$converterDirectory").run {
            mkdirs()
            File("$absolutePath/$it.java").outputStream()
        }
        println("Generating $converterPackage.$it from $source")
        FileUtil.copy(
            SequenceInputStream("""
                /*
                 * This file is generated by jOOQ DSL.
                 */
                package $converterPackage;


                """.trimIndent().byteInputStream(),
                source.openStream()
            ),
            target
        )
    }
}
