import io.osguima3.jooqdsl.model.converter.Converter;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ DSL.
 */
@Generated(
    value = "https://github.com/Osguima3/jooq-dsl-maven-plugin",
    comments = "This class is generated by jOOQ DSL"
)
public class ConverterAdapter<T, U> implements org.jooq.Converter<T, U> {

    private Converter<T, U> converter;

    private Class<T> fromType;

    private Class<U> toType;

    public ConverterAdapter(Converter<T, U> converter, Class<T> fromType, Class<U> toType) {
        this.converter = converter;
        this.fromType = fromType;
        this.toType = toType;
    }

    @Override
    public U from(T databaseObject) {
        return databaseObject == null ? null : converter.from(databaseObject);
    }

    @Override
    public T to(U userObject) {
        return userObject == null ? null : converter.to(userObject);
    }

    @Override
    public Class<T> fromType() {
        return fromType;
    }

    @Override
    public Class<U> toType() {
        return toType;
    }
}
