name: Build jOOQ DSL

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: maven
          distribution: adopt
          java-version: 17

      - name: Build project
        run: mvn -B clean compile verify
