name: Build jOOQ DSL

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: adopt
        java-version: 11

    - name: Build maven project
      run: mvn -B clean compile verify
      working-directory: maven

    - name: Build gradle project
      run: ./gradlew clean build
      working-directory: gradle
