name: Publish jOOQ DSL to Maven Central

on:
#  release:
#    types: [ published ]
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: adopt
          java-version: 21

      - id: install-secret-key
        name: Install GPG secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import

      - name: Deploy
        run: ./gradlew publish -Prelease
        env:
          SONATYPE_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
